### ISSUE TITLE
Improve content displayed before selecting a course

### ISSUE THREAD

**Issue by sebthedev** [sebthedev/PrincetonCourses#20]
At the moment, after logging in but before you select a course, you see a screen like this:
<img width="1278" alt="screen shot 2017-04-06 at 17 15 20" src="https://cloud.githubusercontent.com/assets/1550185/24775876/a333476a-1aec-11e7-9f0c-e82b89acc45a.png">

I think that we should remove the "Past Semesters", "Numeric Evaluations", and "Student Comments" placeholders.

Then the question is what should put in its place? We could add tips on how to use Princeton Courses? Some features we could write about include favoriting courses, voting on evaluation comments, and searching.

Thoughts?

**Comment by bnsuoh** [comment]
Currently, we have a placeholder Princeton Shield in the body. Mel suggested the idea of showing the updates on that page instead of on a popup. Some other possible options are: A feeling lucky page of a random course and, as Seb said, tips on using the tool. 
Although, I'm personally leaning towards having the page empty with a Princeton Shield, to avoid clutter and to direct the user's attention to the search pane on the left.

**Comment by cgolner** [comment]
I think a feeling lucky tool is not likely to have any real effect on a
user's decision to take a class, but the space *would* be great for listing
updates and giving tips for use. Maybe the tips/instructions on the middle
since it's closer to the search pane, and the updates on the right.
