### ISSUE TITLE
returning number of spots available/taken in search results and favorites

### ISSUE THREAD

**Issue by melyshu** [sebthedev/PrincetonCourses#67]
might be useful during course selection to see this information in the search pane itself

**Comment by sebthedev** [comment]
As 375cb9879821b7e2e3bbac0b905bd313bd0ad7d2 explains, Courses returned on API endpoints now contain an “open” property. This will be true if, for each of the courses section types (lecture, precept, etc…) there is at least one section that is open.

@melyshu I'm aware that this isn't exactly what you were requesting, but I hope you'll be able to use this information. Re-open this issue if you need further changes.

**Comment by melyshu** [comment]
i guess number of spots available/taken is harder to do... although I still think it might be nice to see from the search pane. The front end should be working to indicate (at this point in time) only those courses which are not open, but I don't think that course.open was defined for any of the search results. @sebthedev  could you check if this is the case?

**Comment by sebthedev** [comment]
Courses now have the `.open` property, and it's correctly showing on the front-end on `dev` right now.

The reason it wasn't showing before is because these changes take place in the importer script. Every 10 minutes, `master`'s version of the importer script is run. I subsequently separately ran my script which updates the dev database with the latest data from the production database, which had the impact that the `.open` info wasn't in the dev database.

**Comment by melyshu** [comment]
https://www.princetoncourses.com/course/1182005149?search=phy209&semester=1182&sort=relevance is a funny one -- all labs cancelled but definitely not full.
